version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.0.2
workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: master
          mapping: |
            project-one/.* project-one-modified true
            project-two/.* project-two-modified true
          config-path: .circleci/workflows.yml



# jobs:
#   say-hello:

#     docker:
#       - image: cimg/base:stable

#     steps:
#       - checkout
#       - run:
#           name: "Say hello"
#           command: "echo Hello, World!"


# workflows:
#   say-hello-workflow:
#     jobs:
#       - say-hello
